/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantSlugRouteRouteImport } from './routes/t/$tenantSlug/route'
import { Route as TTenantSlugIndexRouteImport } from './routes/t/$tenantSlug/index'
import { Route as TTenantSlugContentTypesIndexRouteImport } from './routes/t/$tenantSlug/content-types/index'
import { Route as TTenantSlugContentTypesNewRouteImport } from './routes/t/$tenantSlug/content-types/new'
import { Route as TTenantSlugRecordsTypeKeyIndexRouteImport } from './routes/t/$tenantSlug/records/$typeKey/index'
import { Route as TTenantSlugRecordsTypeKeyNewRouteImport } from './routes/t/$tenantSlug/records/$typeKey/new'
import { Route as TTenantSlugRecordsTypeKeyRecordIdRouteImport } from './routes/t/$tenantSlug/records/$typeKey/$recordId'
import { Route as TTenantSlugContentTypesTypeKeyEditRouteImport } from './routes/t/$tenantSlug/content-types/$typeKey.edit'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugRouteRoute = TTenantSlugRouteRouteImport.update({
  id: '/t/$tenantSlug',
  path: '/t/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSlugIndexRoute = TTenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTenantSlugRouteRoute,
} as any)
const TTenantSlugContentTypesIndexRoute =
  TTenantSlugContentTypesIndexRouteImport.update({
    id: '/content-types/',
    path: '/content-types/',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)
const TTenantSlugContentTypesNewRoute =
  TTenantSlugContentTypesNewRouteImport.update({
    id: '/content-types/new',
    path: '/content-types/new',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)
const TTenantSlugRecordsTypeKeyIndexRoute =
  TTenantSlugRecordsTypeKeyIndexRouteImport.update({
    id: '/records/$typeKey/',
    path: '/records/$typeKey/',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)
const TTenantSlugRecordsTypeKeyNewRoute =
  TTenantSlugRecordsTypeKeyNewRouteImport.update({
    id: '/records/$typeKey/new',
    path: '/records/$typeKey/new',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)
const TTenantSlugRecordsTypeKeyRecordIdRoute =
  TTenantSlugRecordsTypeKeyRecordIdRouteImport.update({
    id: '/records/$typeKey/$recordId',
    path: '/records/$typeKey/$recordId',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)
const TTenantSlugContentTypesTypeKeyEditRoute =
  TTenantSlugContentTypesTypeKeyEditRouteImport.update({
    id: '/content-types/$typeKey/edit',
    path: '/content-types/$typeKey/edit',
    getParentRoute: () => TTenantSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteRouteWithChildren
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/content-types/new': typeof TTenantSlugContentTypesNewRoute
  '/t/$tenantSlug/content-types/': typeof TTenantSlugContentTypesIndexRoute
  '/t/$tenantSlug/content-types/$typeKey/edit': typeof TTenantSlugContentTypesTypeKeyEditRoute
  '/t/$tenantSlug/records/$typeKey/$recordId': typeof TTenantSlugRecordsTypeKeyRecordIdRoute
  '/t/$tenantSlug/records/$typeKey/new': typeof TTenantSlugRecordsTypeKeyNewRoute
  '/t/$tenantSlug/records/$typeKey/': typeof TTenantSlugRecordsTypeKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantSlug': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/content-types/new': typeof TTenantSlugContentTypesNewRoute
  '/t/$tenantSlug/content-types': typeof TTenantSlugContentTypesIndexRoute
  '/t/$tenantSlug/content-types/$typeKey/edit': typeof TTenantSlugContentTypesTypeKeyEditRoute
  '/t/$tenantSlug/records/$typeKey/$recordId': typeof TTenantSlugRecordsTypeKeyRecordIdRoute
  '/t/$tenantSlug/records/$typeKey/new': typeof TTenantSlugRecordsTypeKeyNewRoute
  '/t/$tenantSlug/records/$typeKey': typeof TTenantSlugRecordsTypeKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tenants': typeof TenantsRoute
  '/t/$tenantSlug': typeof TTenantSlugRouteRouteWithChildren
  '/t/$tenantSlug/': typeof TTenantSlugIndexRoute
  '/t/$tenantSlug/content-types/new': typeof TTenantSlugContentTypesNewRoute
  '/t/$tenantSlug/content-types/': typeof TTenantSlugContentTypesIndexRoute
  '/t/$tenantSlug/content-types/$typeKey/edit': typeof TTenantSlugContentTypesTypeKeyEditRoute
  '/t/$tenantSlug/records/$typeKey/$recordId': typeof TTenantSlugRecordsTypeKeyRecordIdRoute
  '/t/$tenantSlug/records/$typeKey/new': typeof TTenantSlugRecordsTypeKeyNewRoute
  '/t/$tenantSlug/records/$typeKey/': typeof TTenantSlugRecordsTypeKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/tenants'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/'
    | '/t/$tenantSlug/content-types/new'
    | '/t/$tenantSlug/content-types/'
    | '/t/$tenantSlug/content-types/$typeKey/edit'
    | '/t/$tenantSlug/records/$typeKey/$recordId'
    | '/t/$tenantSlug/records/$typeKey/new'
    | '/t/$tenantSlug/records/$typeKey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/tenants'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/content-types/new'
    | '/t/$tenantSlug/content-types'
    | '/t/$tenantSlug/content-types/$typeKey/edit'
    | '/t/$tenantSlug/records/$typeKey/$recordId'
    | '/t/$tenantSlug/records/$typeKey/new'
    | '/t/$tenantSlug/records/$typeKey'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/tenants'
    | '/t/$tenantSlug'
    | '/t/$tenantSlug/'
    | '/t/$tenantSlug/content-types/new'
    | '/t/$tenantSlug/content-types/'
    | '/t/$tenantSlug/content-types/$typeKey/edit'
    | '/t/$tenantSlug/records/$typeKey/$recordId'
    | '/t/$tenantSlug/records/$typeKey/new'
    | '/t/$tenantSlug/records/$typeKey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TenantsRoute: typeof TenantsRoute
  TTenantSlugRouteRoute: typeof TTenantSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug': {
      id: '/t/$tenantSlug'
      path: '/t/$tenantSlug'
      fullPath: '/t/$tenantSlug'
      preLoaderRoute: typeof TTenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenantSlug/': {
      id: '/t/$tenantSlug/'
      path: '/'
      fullPath: '/t/$tenantSlug/'
      preLoaderRoute: typeof TTenantSlugIndexRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/content-types/': {
      id: '/t/$tenantSlug/content-types/'
      path: '/content-types'
      fullPath: '/t/$tenantSlug/content-types/'
      preLoaderRoute: typeof TTenantSlugContentTypesIndexRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/content-types/new': {
      id: '/t/$tenantSlug/content-types/new'
      path: '/content-types/new'
      fullPath: '/t/$tenantSlug/content-types/new'
      preLoaderRoute: typeof TTenantSlugContentTypesNewRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/records/$typeKey/': {
      id: '/t/$tenantSlug/records/$typeKey/'
      path: '/records/$typeKey'
      fullPath: '/t/$tenantSlug/records/$typeKey/'
      preLoaderRoute: typeof TTenantSlugRecordsTypeKeyIndexRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/records/$typeKey/new': {
      id: '/t/$tenantSlug/records/$typeKey/new'
      path: '/records/$typeKey/new'
      fullPath: '/t/$tenantSlug/records/$typeKey/new'
      preLoaderRoute: typeof TTenantSlugRecordsTypeKeyNewRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/records/$typeKey/$recordId': {
      id: '/t/$tenantSlug/records/$typeKey/$recordId'
      path: '/records/$typeKey/$recordId'
      fullPath: '/t/$tenantSlug/records/$typeKey/$recordId'
      preLoaderRoute: typeof TTenantSlugRecordsTypeKeyRecordIdRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
    '/t/$tenantSlug/content-types/$typeKey/edit': {
      id: '/t/$tenantSlug/content-types/$typeKey/edit'
      path: '/content-types/$typeKey/edit'
      fullPath: '/t/$tenantSlug/content-types/$typeKey/edit'
      preLoaderRoute: typeof TTenantSlugContentTypesTypeKeyEditRouteImport
      parentRoute: typeof TTenantSlugRouteRoute
    }
  }
}

interface TTenantSlugRouteRouteChildren {
  TTenantSlugIndexRoute: typeof TTenantSlugIndexRoute
  TTenantSlugContentTypesNewRoute: typeof TTenantSlugContentTypesNewRoute
  TTenantSlugContentTypesIndexRoute: typeof TTenantSlugContentTypesIndexRoute
  TTenantSlugContentTypesTypeKeyEditRoute: typeof TTenantSlugContentTypesTypeKeyEditRoute
  TTenantSlugRecordsTypeKeyRecordIdRoute: typeof TTenantSlugRecordsTypeKeyRecordIdRoute
  TTenantSlugRecordsTypeKeyNewRoute: typeof TTenantSlugRecordsTypeKeyNewRoute
  TTenantSlugRecordsTypeKeyIndexRoute: typeof TTenantSlugRecordsTypeKeyIndexRoute
}

const TTenantSlugRouteRouteChildren: TTenantSlugRouteRouteChildren = {
  TTenantSlugIndexRoute: TTenantSlugIndexRoute,
  TTenantSlugContentTypesNewRoute: TTenantSlugContentTypesNewRoute,
  TTenantSlugContentTypesIndexRoute: TTenantSlugContentTypesIndexRoute,
  TTenantSlugContentTypesTypeKeyEditRoute:
    TTenantSlugContentTypesTypeKeyEditRoute,
  TTenantSlugRecordsTypeKeyRecordIdRoute:
    TTenantSlugRecordsTypeKeyRecordIdRoute,
  TTenantSlugRecordsTypeKeyNewRoute: TTenantSlugRecordsTypeKeyNewRoute,
  TTenantSlugRecordsTypeKeyIndexRoute: TTenantSlugRecordsTypeKeyIndexRoute,
}

const TTenantSlugRouteRouteWithChildren =
  TTenantSlugRouteRoute._addFileChildren(TTenantSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TenantsRoute: TenantsRoute,
  TTenantSlugRouteRoute: TTenantSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
